In [1]:
import numpy as np

In [2]:
#creating array from existing list

list_1 = [1, 2, 3, 4, 5]
arr_1 = np.array(list_1)
arr_1

array([1, 2, 3, 4, 5])

In [3]:
# creating 1d array

arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d

arr_1d_placeholder = np.array(5)
arr_1d_placeholder

array(5)

In [4]:
# 2d array

arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 3d array

arr_3d = np.array([
    [["a", "b", "c"],
    ["d", "e", "f"]],
    
    [["x", "y", "z"],
    ["p", "q", "r"]]
])
arr_3d

array([[['a', 'b', 'c'],
        ['d', 'e', 'f']],

       [['x', 'y', 'z'],
        ['p', 'q', 'r']]], dtype='<U1')

In [6]:
# random array generation 1d
arr_rand = np.random.random(3)
arr_rand

array([0.39128634, 0.19046232, 0.26573777])

In [7]:
# random array generation for n-dimensional
arr_rand_nd = np.random.rand(2, 3)
arr_rand_nd

arr_rand_3d = np.random.randint(2, 10, 5) # from 2 to 10, generate 5 random numbers
arr_rand_3d

array([9, 5, 5, 4, 5])

In [8]:
# reshape

arr_reshape = np.arange(2, 100, 5).reshape(2, 5, 2)
arr_reshape

array([[[ 2,  7],
        [12, 17],
        [22, 27],
        [32, 37],
        [42, 47]],

       [[52, 57],
        [62, 67],
        [72, 77],
        [82, 87],
        [92, 97]]])

In [9]:
# zeros
arr_zeros = np.zeros(5, dtype=int) # arr of one dimension with 5 zeros
arr_zeros

arr_zeros_nd = np.zeros((3, 3, 5), dtype=bool) # false because everything is 0
arr_zeros_nd

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

In [10]:
# ones
arr_ones = np.ones(5, dtype=int) # arr of 1d with 5 ones
arr_ones

arr_ones_nd = np.ones((3, 3, 5), dtype=bool) # true because everything is 1
arr_ones_nd

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [11]:
# empty

arr_empty = np.empty(5) #empty doesnt mean just null, but it allocates the memory for the array and doesnt fill the data, but the data here shown is the data system already had, like background processings or stuff like that
arr_empty

array([1.06791308e-315, 0.00000000e+000, 1.03930495e-315, 1.06312263e-315,
       2.37151510e-322])

In [12]:
# arange

arr_range = np.arange(10) #from 0 to 9
arr_range

arr_range_start_to_end = np.arange(19, 27) # from 19 to 26
arr_range_start_to_end

arr_range_steps = np.arange(2, 21, 2) # from 2 to 20 but with 2 steps (even numbers in this case)
arr_range_steps

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
# linspace
