# **Array Manipulation**

Here, I will learn different methods of modiying the arrays while also learning about the arithmetic operations. 

## **1. Value Asignment and Conditional Updates**

This is fundamental because it's how you directly alter the data stored within your arrays. With three main ways:

- **Direct Element Assignment**: Changing one specific value.
- **Slice Assignment**: Changing a range of values.
- **Boolean Mask Assignment**: Changing values based on a condition.

In [1]:
import numpy as np

In [2]:
assign_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) #1d array

assign_2d = np.array([ #2d array
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

assign_3d = np.array([ #3d array
    [[100, 200, 300],
        [400, 500, 600]],

    [[719, 819, 919],
    [1019, 1119, 1129]]
])

### **Direct Element Assignment**

Changing one specific value

In [3]:
# this is easy, same as we did in indexing

assign_1d [7] = 999 # changes the 7th index or 8th element -> from 80 to 999
assign_1d

assign_2d [1, -1] = 918 # changes the last element of the 2nd row -> from 8 to 918
assign_2d

assign_3d [0, 1, 2] = 1 # changes the 3rd element located in second row of 1st slice -> from 600 to 1
assign_3d

array([[[ 100,  200,  300],
        [ 400,  500,    1]],

       [[ 719,  819,  919],
        [1019, 1119, 1129]]])

### **Slice Assignment**

What if we want to change the multiple values at once? Like entire rows or from x-index to y-index?

In [4]:
print(f"1d: {assign_1d}")
print(f"2d: {assign_2d}")
print(f"3d: {assign_3d}")

1d: [ 10  20  30  40  50  60  70 999  90 100]
2d: [[  1   2   3   4]
 [  5   6   7 918]
 [  9  10  11  12]]
3d: [[[ 100  200  300]
  [ 400  500    1]]

 [[ 719  819  919]
  [1019 1119 1129]]]


In [5]:
# this is same as i read on slicing in reading-array

assign_1d [0:3] = 39 # gives updated array with changed value of 39 in index 1, 2 and 3
assign_1d

assign_2d [:, 2] = 44 # gives updated array with changed value of 44 in 2nd index of all rows
assign_2d

assign_3d [0, 1, 0:2] = [1, 1] # changed value of [1, 1] in 0 and 1 index of 2nd row of 1st slice
assign_3d

array([[[ 100,  200,  300],
        [   1,    1,    1]],

       [[ 719,  819,  919],
        [1019, 1119, 1129]]])

### **Boolean Mask Assignment**

Changing values based on a condition.

In [6]:
print(f"1d: {assign_1d}")
print(f"2d: {assign_2d}")
print(f"3d: {assign_3d}")

1d: [ 39  39  39  40  50  60  70 999  90 100]
2d: [[  1   2  44   4]
 [  5   6  44 918]
 [  9  10  44  12]]
3d: [[[ 100  200  300]
  [   1    1    1]]

 [[ 719  819  919]
  [1019 1119 1129]]]


In [7]:
# this is also same as boolean indexing i read

assign_1d [assign_1d != 39] = 0
assign_1d

assign_2d [(assign_2d [1, 2] > 20) & (assign_2d [-1, 1] < 10)] = 0
assign_2d

assign_2d [(assign_2d [:, 2] == 0) | (assign_2d [:, 2] < 50)] = 1
assign_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## **2. Reshaping and Dimension Manipulation**

- changing an array's shape and flattening the arr >= 2 to 1d array
- adding new dimension/s
- transposing

### **Changing Array Shape**

In [8]:
arr_1d = np.arange(24) # 1d array from 0 to 23
arr_2d = np.arange(24).reshape(4, 6) # 2d array with 4 rows and 6 comlumns each from 0 to 23
arr_3d = np.arange(24).reshape(2, 3, 4) # 3d array with 2 slices, 3 rows each and 4 columns

print(arr_1d)
print(arr_2d)
print(arr_3d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [9]:
# changing the shape of 1d array to 2d and 3d array

# using .reshape()

one_2d = arr_1d.reshape(2, 12) # 2 rows, 12 columns each
one_2d

one_2d_1 = arr_1d.reshape(3, 8) # 3 rows, 8 columns each
one_2d_1

one_2d_2 = arr_1d.reshape(12, 2) # 12 rows, 2 columns each
one_2d_2

one_3d = arr_1d.reshape(2, 4, 3) # 2 slices, 4 rows each with 3 columns
one_3d

one_3d_1 = arr_1d.reshape(4, 3, 2) # 4 slices, 3 rows each with 2 columns
one_3d_1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [10]:
# 2d to 3d and 1d

two_3d = arr_2d.reshape(3, 4, 2)
two_3d

two_3d_1 = arr_2d.reshape(6, 2, 2)
two_3d_1

# 2d to 1d

# we can use either .ravel() or .flatten() or .reshape(-1)

two_1d = arr_2d.ravel()
two_1d

two_1d_1 = arr_2d.flatten()
two_1d_1

two_1d_2 = arr_2d.reshape(-1)
two_1d_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
# 3d to 2d

three_2d = arr_3d.reshape(6, 4)
three_2d

three_2d_1 = arr_3d.reshape(4, 6)
three_2d_1

# 3d to 1d

three_1d = arr_3d.reshape(-1)
three_1d

# we can also use .ravel and .flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### **Adding new Dimensions**

In [12]:
newd_1d = np.arange(24) # 1d array from 0 to 23
newd_2d = np.arange(24).reshape(4, 6) # 2d array with 4 rows and 6 comlumns each from 0 to 23
newd_3d = np.arange(24).reshape(2, 3, 4) # 3d array with 2 slices, 3 rows each and 4 columns

In [13]:
# adding new dimension in 1d array, which will make it 2d

newd_as_row = newd_1d[None, :]
newd_as_row

newd_as_col = newd_1d[:, np.newaxis]
newd_as_col

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [14]:
# adding new dimension in 2d array, which will make it 3d

newd_in_2d_as_row = newd_2d[None, :, :]
newd_in_2d_as_row

newd_in_2d_as_col = newd_2d[:, :, np.newaxis]
newd_in_2d_as_col

# same for 3d 

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23]]])

### **Transposing**

In [15]:
# .T, which transposes the order of axes, rows element to column and vice versa (applies to arr > 1)
t_2d = np.arange(24).reshape(4, 6)
t_2d.shape
t_2d.T.shape # -> from (4,6) to (6,4)

t_3d = np.arange(24).reshape(2, 4, 3)
t_3d.T # from (2, 4, 3) to (3, 4, 2)

array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

In [16]:
# .transpose, flexible than .T

transpose_3d = np.arange(24).reshape(2, 4, 3)
print(transpose_3d)

new = np.transpose(transpose_3d, axes=(0, 2, 1)) # keep the slices of same number, exchange the number of rows and columns with each other
new

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


array([[[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]],

       [[12, 15, 18, 21],
        [13, 16, 19, 22],
        [14, 17, 20, 23]]])

## **3. Array Combination and Alteration**

Focuses on operations that change the size or number of elements in your arrays by combining multiple arrays, or by adding/removing elements. Topics included are:

- Concatenation
- Vertical Stacking
- Horizontal Stacking
- adding elements

### **Concatenation**

Basically, to add multiple arrays in one single array we use np.concatenate(). But where to add the array if it's multi-dimensional? As row, as column, as slice? That's why we use axes(0, 1, 2, ..., n). But, axes are always not similar in all nd-arrays. For example, for 2d array row is axis-0 where was for 3d arrays it's axis-1.

Simply put, axis-0 is always the first dimension for that array. Remember? When we used to slice?
For 3-d array we used to say, [x-slice] [y-row] [z-column], we are saying [axis-0] [axis-1] [axis-2]

In [17]:
x = np.arange(0, 6)
y = np.arange(0, 12).reshape(4, 3)
z = np.arange(0, 24).reshape(3, 2, 4)

print(x)
print(y)
print(z)

a = np.array([1, 2, 3, 4, 5])
b = np.array([[9, 9, 9, 9]])
c = np.array([100, 100, 100])
d = np.array([
    [69],
    [69],
    [69],
    [69],
])


[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [18]:
x_concat = np.concatenate((x, a))
x_concat

# y_axis0 = np.concatenate((y, c), axis = 0) # it shows error. because we used 1d array to concatenate with 2d array. hmm interesting i am making such mistakes
# y_axis0

array([0, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [19]:
c = np.array([[100, 100, 100]])

y_axis0 = np.concatenate((y, c), axis=0) # add a row 
y_axis0

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [100, 100, 100]])

In [20]:
y_axis1 = np.concatenate((y, d), axis=1) # add a column
y_axis1

array([[ 0,  1,  2, 69],
       [ 3,  4,  5, 69],
       [ 6,  7,  8, 69],
       [ 9, 10, 11, 69]])

### **Vertical Stacking (.vstack)**

It's just the specialized and concise version of np.concatenate((arr, arr2), axis=0) for 2d arrays

In [21]:
varr = np.arange(0, 12).reshape(3, 4)
addin = np.arange(4, 8).reshape(1, 4)

In [22]:
vstacked = np.vstack((varr, addin)) # adds rows
vstacked

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

### **Horizantal Stacking (.hstack)**

In [23]:
harr = np.arange(0, 12).reshape(3, 4)
addin = np.arange(4, 7).reshape(3, 1)

In [24]:
hstacked = np.hstack((harr, addin)) # adds columns but number of rows has to be same 
hstacked

array([[ 0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  5],
       [ 8,  9, 10, 11,  6]])

## **4. Element-wise Operations and Broadcasting**

We will focus on some arithmetic operations that exists on numpy. And then we will get to broadcasting. 

- Basic Arithmetic (+, -, *, /, **)
- Universal Functions (ufuncs like np.sqrt, np.log, np.exp, np.sin, etc.)
- Understanding Broadcasting Rules

### **Arithmetic Operations**

In [25]:
arith1 = np.array([1, 2, 3, 4])
arith2 = np.array([5, 6, 7, 8])
print(f"{arith1} \n \n{arith2} \n")

ar2d1 = np.arange(100, 200, 5).reshape(4, 5)
ar2d2 = np.arange(1, 100, 5).reshape(4, 5)
print(f"{ar2d1} \n \n{ar2d2}")

[1 2 3 4] 
 
[5 6 7 8] 

[[100 105 110 115 120]
 [125 130 135 140 145]
 [150 155 160 165 170]
 [175 180 185 190 195]] 
 
[[ 1  6 11 16 21]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]]


In [26]:
# adding

add1 = np.add(arith1, arith2) # or we can use arr1 + arr2
print(add1)
print("\n")

add2 = np.add(ar2d1, ar2d2)
print(add2)
print("\n")

# subtract

sub1 = np.subtract(arith1, arith2)
print(sub1)
print("\n")

sub2 = np.subtract(ar2d1, ar2d2)
print(sub2)
print("\n")

# multiply

mul1 = np.multiply(arith1, arith2)
print(mul1)
print("\n")

mul2 = np.multiply(ar2d1, ar2d2)
print(mul2)
print("\n")

# division

div1 = np.divide(arith1, arith2)
print(div1)
print("\n")

div2 = np.divide(ar2d1, ar2d2)
print(div2)
print("\n")

# power

pow1 = arith1 ** 3
print(pow1)
print("\n")

pow2 = ar2d2 ** 3
print(pow2)
print("\n")

[ 6  8 10 12]


[[101 111 121 131 141]
 [151 161 171 181 191]
 [201 211 221 231 241]
 [251 261 271 281 291]]


[-4 -4 -4 -4]


[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


[ 5 12 21 32]


[[  100   630  1210  1840  2520]
 [ 3250  4030  4860  5740  6670]
 [ 7650  8680  9760 10890 12070]
 [13300 14580 15910 17290 18720]]


[0.2        0.33333333 0.42857143 0.5       ]


[[100.          17.5         10.           7.1875       5.71428571]
 [  4.80769231   4.19354839   3.75         3.41463415   3.15217391]
 [  2.94117647   2.76785714   2.62295082   2.5          2.3943662 ]
 [  2.30263158   2.22222222   2.15116279   2.08791209   2.03125   ]]


[ 1  8 27 64]


[[     1    216   1331   4096   9261]
 [ 17576  29791  46656  68921  97336]
 [132651 175616 226981 287496 357911]
 [438976 531441 636056 753571 884736]]




### **Universal Operations**

In [27]:
uni1 = np.array([1, 2, 3, 4])
uni2 = np.array([5, 6, 7, 8])
print(f"{uni1} \n \n{uni2} \n")

uni2da = np.arange(100, 200, 5).reshape(4, 5)
uni2db = np.arange(1, 100, 5).reshape(4, 5)
print(f"{uni2da} \n \n{uni2db}")

[1 2 3 4] 
 
[5 6 7 8] 

[[100 105 110 115 120]
 [125 130 135 140 145]
 [150 155 160 165 170]
 [175 180 185 190 195]] 
 
[[ 1  6 11 16 21]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]]


In [28]:
# square root

sq1 = (np.sqrt(uni1))
print(sq1)
print("\n")

sq2 = np.sqrt(uni2da)
print(sq2)
print("\n")

# exponential

exp1 = (np.exp(uni1)) # this exponential is not equal to power, but is Euler number (e) founded by Jacob Bernoulii, so it's e^x
print(exp1)
print("\n")

exp2 = np.exp(uni2db)
print(exp2)
print("\n")

#logarithm - log(x)

log1 = (np.log(uni1))
print(log1)
print("\n")

log2 = np.log(uni2da)
print(log2)
print("\n")

# trignometric (sin, cos, tan)

sin1 = (np.sin(uni1))
print(sin1)
print("\n")

cos1 = np.cos(uni2)
print(cos1)
print("\n")

tan1 = np.tan(uni2da)
print(tan1)
print("\n")

# absolute (abs) Removes the negative sign from negative numbers. For complex numbers, it returns the magnitude.

abs1 = np.array([-1, -2, 8, -9, 0])
res_abs1 = np.abs(abs1)
print(res_abs1)
print("\n")

# ceiling (.ceil) roundoffs to the nearest smallest integer greater or euqal to it, if 3.123, it will round off to 14

ceil1 = np.random.uniform(10, 20, size=(2, 3)) # generates the random float numbers from 10 to 20 with 2d array
print(ceil1)
result = np.ceil(ceil1)
print(result)
print("\n")

# flooring (.floor) just opposite to ceil, it will roundoff to nearest integer smaller to it. if 2.9, it will be 2

floor1 = np.floor(3.1415)
print(floor1)
print("\n")

# rounding (.round) 

round1 = np.round(3.657, decimals=0) # rounds off to the nearest possible integer
print(round1)
print("\n")

# maximum and minimum, it does the element-wise ops in two arrays and find the maximum/minimum between two indexes of each array (takes two arguments and the array dimensions should be the same)

max1 = np.random.randint(10, 20, size=(2,3))
max2 = np.random.randint(20, 30, size=(2,3))
print(f"{max1} \n{max2}\n")

res1 = np.maximum(max1, max2)
print(f"{res1}\n")

res2 = np.minimum(max1, max2)
print(f"{res2}\n")

[1.         1.41421356 1.73205081 2.        ]


[[10.         10.24695077 10.48808848 10.72380529 10.95445115]
 [11.18033989 11.40175425 11.61895004 11.83215957 12.04159458]
 [12.24744871 12.4498996  12.64911064 12.84523258 13.03840481]
 [13.22875656 13.41640786 13.60147051 13.78404875 13.96424004]]


[ 2.71828183  7.3890561  20.08553692 54.59815003]


[[2.71828183e+00 4.03428793e+02 5.98741417e+04 8.88611052e+06
  1.31881573e+09]
 [1.95729609e+11 2.90488497e+13 4.31123155e+15 6.39843494e+17
  9.49611942e+19]
 [1.40934908e+22 2.09165950e+24 3.10429794e+26 4.60718663e+28
  6.83767123e+30]
 [1.01480039e+33 1.50609731e+35 2.23524660e+37 3.31740010e+39
  4.92345829e+41]]


[0.         0.69314718 1.09861229 1.38629436]


[[4.60517019 4.65396035 4.70048037 4.74493213 4.78749174]
 [4.82831374 4.86753445 4.90527478 4.94164242 4.97673374]
 [5.01063529 5.04342512 5.07517382 5.10594547 5.13579844]
 [5.16478597 5.19295685 5.22035583 5.24702407 5.27299956]]


[ 0.84147098  0.90929743  0.14112001 -0

### **Broadcasting**

The numpy way to deal with the arithmetic operations of different shapes and dimensions.

The Broadcasting Rules:

To determine if two arrays (Array A and Array B) are compatible for broadcasting, NumPy compares their shapes dimension by dimension, starting from the trailing (rightmost) dimension and moving left.

Two dimensions are compatible if:

    They are equal, OR

    One of the dimensions is 1.

If these rules are met, the arrays can be broadcast. If not, a ValueError (specifically, "operands could not be broadcast together") is raised.

The resulting array's shape will be the maximum size along each dimension of the input arrays.

Examples of Broadcasting Rules in Action

Example 1: Compatible Shapes (Equal Dimensions)

    A: (4, 3)

    B: (4, 3)

    Trailing dimensions: 3 and 3 (Equal) - Compatible.

    Next dimensions: 4 and 4 (Equal) - Compatible.

Result: (4, 3)

Example 2: Compatible (One dimension is 1)

    A: (4, 3)

    B: (1, 3)

    Trailing dimensions: 3 and 3 (Equal) - Compatible.

    Next dimensions: 4 and 1 (One is 1) - Compatible.

Result: (4, 3) (The dimension of size 1 is stretched to 4).

Example 3: Compatible (Scalar or 1D array with matching trailing dimension)

    A: (4, 3)

    B: (3,) (NumPy implicitly treats this as (1, 3) when broadcasting against 2D)

    Trailing dimensions: 3 and 3 (Equal) - Compatible.

    Next dimensions: 4 and 1 (One is 1) - Compatible.

Result: (4, 3)

Example 4: Incompatible Shapes

    A: (4, 3)

    B: (4,)

    Trailing dimensions: 3 and 4 (Not equal, neither is 1) - Incompatible.

Result: ValueError: operands could not be broadcast together with shapes (4,3) (4,)

In [29]:
bro1 = np.random.randint(10, 30, size=(2, 3))
print(bro1)
bro2 = np.random.randint(10, 30, size=(3, ))
print(bro2)
print(bro2.shape)

[[17 12 19]
 [29 12 16]]
[24 23 20]
(3,)


In [30]:
# to do the ops between 2d and 1d array, first we will do row to row and then column to column

row = bro1 + bro2 # success because 1d array is (3, ) which numpy takes as (1, 3)
print(row)
print("\n")

# but for bro1 and bro2 to be operated columnwise, we have to reshape our bro1 and add column to bro2

bro1reshape = bro1.reshape(3,2)
print(bro1reshape)
print(bro1reshape.shape)
print("\n")

bro2reshape = bro2[:, None]
print(bro2reshape)
print(bro2reshape.shape)
print("\n")

add = bro1reshape + bro2reshape
print(add)

[[41 35 39]
 [53 35 36]]


[[17 12]
 [19 29]
 [12 16]]
(3, 2)


[[24]
 [23]
 [20]]
(3, 1)


[[41 36]
 [42 52]
 [32 36]]


## **5. Statistical Methods**

Now let's dive into statistical method like aggregation functions(mean, median, etc), min/max, standard deviation, etc.

* Mean (.mean())
* Sum (.sum())
* Min/Max (.min(), .max())
* Standard Deviation (.std())
* Median (np.median())
* Using the axis parameter for directional aggregation

In [31]:
stat1 = np.arange(10, 20)
stat2 = np.random.randint(10, 500, size=(4, 5), dtype="int")
stat3 = np.random.randint(10, 700, size=(3, 4, 5), dtype="int")

print(stat1)
print("\n")
print(stat2)
print("\n")
print(stat3)
print("\n")

[10 11 12 13 14 15 16 17 18 19]


[[146 146 149 474 294]
 [330 449 275 270 263]
 [ 86 363 285 410 237]
 [ 33 487 274 300 276]]


[[[284  94 218 113  32]
  [197 146 619 594 556]
  [390 226 685 422 684]
  [368 381 230 471 624]]

 [[408 270 270 214 640]
  [639 612 269  97 660]
  [ 40  88 327 285 344]
  [104 623 295 345 506]]

 [[620 412 613  55 334]
  [144 177 685 431 391]
  [ 21 193 528 698 341]
  [446 676 345 519  98]]]




In [32]:
# sum
sum1 = np.sum(stat1)
sum2 = np.sum(stat2)
sum3 = np.sum(stat3)
print(f"{sum1}, {sum2}, {sum3}")

# mean
mean1 = np.mean(stat1)
mean2 = np.mean(stat2)
mean3 = np.mean(stat3)
print(f"{mean1}, {mean2}, {mean3}")

# median
med1 = np.median(stat1)
med2 = np.median(stat2)
med3 = np.median(stat3)
print(f"{med1}, {med2}, {med3}")

# standard deviation
std1 = np.std(stat1)
std2 = np.std(stat2)
std3 = np.std(stat3)
print(f"{std1}, {std2}, {std3}")

# variance of all elements
var1 = np.var(stat1)
var2 = np.var(stat2)
var3 = np.var(stat3)
print(f"{var1}, {var2}, {var3}")

# minimum among all
min1 = np.min(stat1)
min2 = np.min(stat2)
min3 = np.min(stat3)
print(f"{min1}, {min2}, {min3}")

# maximum among all
max1 = np.max(stat1)
max2 = np.max(stat2)
max3 = np.max(stat3)
print(f"{max1}, {max2}, {max3}")

# index of maximum and minimum
ind1 = np.argmin(stat1)
ind2 = np.argmax(stat2)
ind3 = np.argmin(stat3)
print(f"{ind1}, {ind2}, {ind3}")

145, 5547, 22097
14.5, 277.35, 368.28333333333336
14.5, 275.5, 345.0
2.8722813232690143, 120.38449858681973, 204.294729224444
8.25, 14492.427500000002, 41736.33638888889
10, 33, 21
19, 487, 698
0, 16, 50
