# **Array Manipulation**

Here, I will learn different methods of modiying the arrays while also learning about the arithmetic operations. 

## **1. Value Asignment and Conditional Updates**

This is fundamental because it's how you directly alter the data stored within your arrays. With three main ways:

- **Direct Element Assignment**: Changing one specific value.
- **Slice Assignment**: Changing a range of values.
- **Boolean Mask Assignment**: Changing values based on a condition.

In [1]:
import numpy as np

In [2]:
assign_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) #1d array

assign_2d = np.array([ #2d array
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

assign_3d = np.array([ #3d array
    [[100, 200, 300],
        [400, 500, 600]],

    [[719, 819, 919],
    [1019, 1119, 1129]]
])

### **Direct Element Assignment**

Changing one specific value

In [3]:
# this is easy, same as we did in indexing

assign_1d [7] = 999 # changes the 7th index or 8th element -> from 80 to 999
assign_1d

assign_2d [1, -1] = 918 # changes the last element of the 2nd row -> from 8 to 918
assign_2d

assign_3d [0, 1, 2] = 1 # changes the 3rd element located in second row of 1st slice -> from 600 to 1
assign_3d

array([[[ 100,  200,  300],
        [ 400,  500,    1]],

       [[ 719,  819,  919],
        [1019, 1119, 1129]]])

### **Slice Assignment**

What if we want to change the multiple values at once? Like entire rows or from x-index to y-index?

In [4]:
print(f"1d: {assign_1d}")
print(f"2d: {assign_2d}")
print(f"3d: {assign_3d}")

1d: [ 10  20  30  40  50  60  70 999  90 100]
2d: [[  1   2   3   4]
 [  5   6   7 918]
 [  9  10  11  12]]
3d: [[[ 100  200  300]
  [ 400  500    1]]

 [[ 719  819  919]
  [1019 1119 1129]]]


In [5]:
# this is same as i read on slicing in reading-array

assign_1d [0:3] = 39 # gives updated array with changed value of 39 in index 1, 2 and 3
assign_1d

assign_2d [:, 2] = 44 # gives updated array with changed value of 44 in 2nd index of all rows
assign_2d

assign_3d [0, 1, 0:2] = [1, 1] # changed value of [1, 1] in 0 and 1 index of 2nd row of 1st slice
assign_3d

array([[[ 100,  200,  300],
        [   1,    1,    1]],

       [[ 719,  819,  919],
        [1019, 1119, 1129]]])

### **Boolean Mask Assignment**

Changing values based on a condition.

In [6]:
print(f"1d: {assign_1d}")
print(f"2d: {assign_2d}")
print(f"3d: {assign_3d}")

1d: [ 39  39  39  40  50  60  70 999  90 100]
2d: [[  1   2  44   4]
 [  5   6  44 918]
 [  9  10  44  12]]
3d: [[[ 100  200  300]
  [   1    1    1]]

 [[ 719  819  919]
  [1019 1119 1129]]]


In [7]:
# this is also same as boolean indexing i read

assign_1d [assign_1d != 39] = 0
assign_1d

assign_2d [(assign_2d [1, 2] > 20) & (assign_2d [-1, 1] < 10)] = 0
assign_2d

assign_2d [(assign_2d [:, 2] == 0) | (assign_2d [:, 2] < 50)] = 1
assign_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## **2. Reshaping and Dimension Manipulation**

- changing an array's shape and flattening the arr >= 2 to 1d array
- adding new dimension/s
- transposing

### **Changing Array Shape**

In [8]:
arr_1d = np.arange(24) # 1d array from 0 to 23
arr_2d = np.arange(24).reshape(4, 6) # 2d array with 4 rows and 6 comlumns each from 0 to 23
arr_3d = np.arange(24).reshape(2, 3, 4) # 3d array with 2 slices, 3 rows each and 4 columns

print(arr_1d)
print(arr_2d)
print(arr_3d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [9]:
# changing the shape of 1d array to 2d and 3d array

# using .reshape()

one_2d = arr_1d.reshape(2, 12) # 2 rows, 12 columns each
one_2d

one_2d_1 = arr_1d.reshape(3, 8) # 3 rows, 8 columns each
one_2d_1

one_2d_2 = arr_1d.reshape(12, 2) # 12 rows, 2 columns each
one_2d_2

one_3d = arr_1d.reshape(2, 4, 3) # 2 slices, 4 rows each with 3 columns
one_3d

one_3d_1 = arr_1d.reshape(4, 3, 2) # 4 slices, 3 rows each with 2 columns
one_3d_1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [10]:
# 2d to 3d and 1d

two_3d = arr_2d.reshape(3, 4, 2)
two_3d

two_3d_1 = arr_2d.reshape(6, 2, 2)
two_3d_1

# 2d to 1d

# we can use either .ravel() or .flatten() or .reshape(-1)

two_1d = arr_2d.ravel()
two_1d

two_1d_1 = arr_2d.flatten()
two_1d_1

two_1d_2 = arr_2d.reshape(-1)
two_1d_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
# 3d to 2d

three_2d = arr_3d.reshape(6, 4)
three_2d

three_2d_1 = arr_3d.reshape(4, 6)
three_2d_1

# 3d to 1d

three_1d = arr_3d.reshape(-1)
three_1d

# we can also use .ravel and .flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### **Adding new Dimensions**

In [12]:
newd_1d = np.arange(24) # 1d array from 0 to 23
newd_2d = np.arange(24).reshape(4, 6) # 2d array with 4 rows and 6 comlumns each from 0 to 23
newd_3d = np.arange(24).reshape(2, 3, 4) # 3d array with 2 slices, 3 rows each and 4 columns

In [13]:
# adding new dimension in 1d array, which will make it 2d

newd_as_row = newd_1d[None, :]
newd_as_row

newd_as_col = newd_1d[:, np.newaxis]
newd_as_col

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [14]:
# adding new dimension in 2d array, which will make it 3d

newd_in_2d_as_row = newd_2d[None, :, :]
newd_in_2d_as_row

newd_in_2d_as_col = newd_2d[:, :, np.newaxis]
newd_in_2d_as_col

# same for 3d 

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23]]])

### **Transposing**

In [15]:
# .T, which transposes the order of axes, rows element to column and vice versa (applies to arr > 1)
t_2d = np.arange(24).reshape(4, 6)
t_2d.shape
t_2d.T.shape # -> from (4,6) to (6,4)

t_3d = np.arange(24).reshape(2, 4, 3)
t_3d.T # from (2, 4, 3) to (3, 4, 2)

array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

In [16]:
# .transpose, flexible than .T

transpose_3d = np.arange(24).reshape(2, 4, 3)
print(transpose_3d)

new = np.transpose(transpose_3d, axes=(0, 2, 1)) # keep the slices of same number, exchange the number of rows and columns with each other
new

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


array([[[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]],

       [[12, 15, 18, 21],
        [13, 16, 19, 22],
        [14, 17, 20, 23]]])