# **Array Manipulation**

Here, I will learn different methods of modiying the arrays while also learning about the arithmetic operations. 

## **1. Value Asignment and Conditional Updates**

This is fundamental because it's how you directly alter the data stored within your arrays. With three main ways:

- **Direct Element Assignment**: Changing one specific value.
- **Slice Assignment**: Changing a range of values.
- **Boolean Mask Assignment**: Changing values based on a condition.

In [1]:
import numpy as np

In [2]:
assign_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) #1d array

assign_2d = np.array([ #2d array
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

assign_3d = np.array([ #3d array
    [[100, 200, 300],
        [400, 500, 600]],

    [[719, 819, 919],
    [1019, 1119, 1129]]
])

### **Direct Element Assignment**

Changing one specific value

In [3]:
# this is easy, same as we did in indexing

assign_1d [7] = 999 # changes the 7th index or 8th element -> from 80 to 999
assign_1d

assign_2d [1, -1] = 918 # changes the last element of the 2nd row -> from 8 to 918
assign_2d

assign_3d [0, 1, 2] = 1 # changes the 3rd element located in second row of 1st slice -> from 600 to 1
assign_3d

array([[[ 100,  200,  300],
        [ 400,  500,    1]],

       [[ 719,  819,  919],
        [1019, 1119, 1129]]])

### **Slice Assignment**

What if we want to change the multiple values at once? Like entire rows or from x-index to y-index?

In [4]:
print(f"1d: {assign_1d}")
print(f"2d: {assign_2d}")
print(f"3d: {assign_3d}")

1d: [ 10  20  30  40  50  60  70 999  90 100]
2d: [[  1   2   3   4]
 [  5   6   7 918]
 [  9  10  11  12]]
3d: [[[ 100  200  300]
  [ 400  500    1]]

 [[ 719  819  919]
  [1019 1119 1129]]]
